### YamlMime:UniversalReference
items:
  - uid: azure-servicefabric.TestErrorChaosEvent
    name: TestErrorChaosEvent
    fullName: TestErrorChaosEvent
    children:
      - azure-servicefabric.TestErrorChaosEvent.reason
    langs:
      - typeScript
    type: interface
    summary: >-
      Describes a Chaos event that gets generated when an unexpected event
      occurs in the Chaos engine.

      For example, due to the cluster snapshot being inconsistent, while
      faulting an entity, Chaos

      found that the entity was already faulted -- which would be an unexpected
      event.
    extends:
      name: azure-servicefabric.ChaosEvent
    package: azure-servicefabric
  - uid: azure-servicefabric.TestErrorChaosEvent.reason
    name: reason
    fullName: reason
    children: []
    langs:
      - typeScript
    type: property
    summary: >-
      Describes why TestErrorChaosEvent was generated. For example, Chaos tries
      to fault a partition

      but finds that the partition is no longer fault tolerant, then a
      TestErrorEvent gets generated

      with the reason stating that the partition is not fault tolerant.
    optional: true
    syntax:
      content: 'reason?: string'
      return:
        type:
          - string
    package: azure-servicefabric
references:
  - uid: azure-servicefabric.ChaosEvent
    name: ChaosEvent
    spec.typeScript:
      - name: ChaosEvent
        fullName: ChaosEvent
        uid: azure-servicefabric.ChaosEvent
